### ISSUE TITLE
The come up

### ISSUE THREAD

**Issue by cloddpierre** [ckz8780/market-toolkit#21]

**Comment by stockaflockaflame** [comment]
This is what I keep getting

**Comment by ckz8780** [comment]
Hi there, not sure if you're able to see this but it's probably because
you're following the repo. You have to unsubscribe from it in your github
settings. I'm not sure exactly where it is but I think it's somewhere in
your notifications settings on the github site. Unfortunately there's no
way for me to unsubscribe you - you have to do it yourself. If you still
can't figure it out drop me a line at ckz8780@gmail.com and I'll try to
help you out. Sorry about that!

**Comment by ckz8780** [comment]
you need to unsubscribe from the repo
